# pnpm-workspace.yaml
# Define qué carpetas son "packages" dentro del monorepo.
# pnpm instalará dependencias de todos estos packages juntos,
# permitiendo que se referencien entre sí con "workspace:*"
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
